### PR TITLE
Update template.py

### PR DESCRIPTION
**Pull request by barrydegraaff**
fixes `milter.error: cannot opensocket`

My name is NOT stuart

### CODE REVIEW

**Comment by sdgathman** [comment]
template.py is documentation.  Yes, using my name is not good.  But using $HOME suggests that that is a good place for the socket - which it isn't.  

I could use $HOME, but have a FIXME comment saying that is not a good home ..  :-)

I could use /tmp/pythonsock with a FIXME.

I could use /var/run/milter/examplesock  - and it wouldn't run until those dirs are created with proper perms.

**Comment by hartwork** [comment]
What about [`XDG_RUNTIME_DIR`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)?
What about module `tempfile`?

**Comment by sdgathman** [comment]
I went with os.path.expanduser and a comment.

**Comment by hartwork** [comment]
For anyone coming here in later: Related commit was 2744175998e587862ca3cbb621940845d6846712

**Comment by barrydegraaff** [comment]
Thank you all for fixing!

**Pull request merged**
